version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"              # location of the dependencies
    schedule:
      interval: "daily"        # or daily/monthly
    target-branch: "development"